//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerSalon.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacteristicsForPC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CharacteristicsForPC()
        {
            this.Assembling = new HashSet<Assembling>();
        }
    
        public int CharacteristicId { get; set; }
        public int ProcessorId { get; set; }
        public int MotherboardId { get; set; }
        public int RamId { get; set; }
        public int VideocardId { get; set; }
        public int PowerUnitId { get; set; }
        public int HddId { get; set; }
        public int CaseId { get; set; }
        public int CoolingId { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assembling> Assembling { get; set; }
        public virtual Cases Cases { get; set; }
        public virtual Cooling Cooling { get; set; }
        public virtual Hdds Hdds { get; set; }
        public virtual Motherboards Motherboards { get; set; }
        public virtual PowerUnits PowerUnits { get; set; }
        public virtual Processors Processors { get; set; }
        public virtual Rams Rams { get; set; }
        public virtual Videocards Videocards { get; set; }
    }
}
