//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerSalon.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedbacks
    {
        public int FeedbackId { get; set; }
        public string Comment { get; set; }
        public int BuyerId { get; set; }
        public int AssemblyId { get; set; }
    
        public virtual Assembling Assembling { get; set; }
        public virtual Buyers Buyers { get; set; }
    }
}
