//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerSalon.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {

        private static Entities _context;
        public Entities()
            : base("name=Entities")
        {
        }

        public static Entities GetContext()
        {
            if (_context == null)
                _context = new Entities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assembling> Assembling { get; set; }
        public virtual DbSet<Buyers> Buyers { get; set; }
        public virtual DbSet<Cases> Cases { get; set; }
        public virtual DbSet<CharacteristicsForPC> CharacteristicsForPC { get; set; }
        public virtual DbSet<Cooling> Cooling { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Feedbacks> Feedbacks { get; set; }
        public virtual DbSet<Hdds> Hdds { get; set; }
        public virtual DbSet<Monitors> Monitors { get; set; }
        public virtual DbSet<Motherboards> Motherboards { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<PowerUnits> PowerUnits { get; set; }
        public virtual DbSet<Processors> Processors { get; set; }
        public virtual DbSet<Rams> Rams { get; set; }
        public virtual DbSet<TypesOfCooling> TypesOfCooling { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Videocards> Videocards { get; set; }
    }
}
